project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
     - text: "Hands-on Exercise"
       menu: 
         - text: "Hands-on Exercise 1.1: Geospatial Data Wrangling with R"
           href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.1.html"
         - text: "Hands-on Exercise 1.2: Choropleth Mapping with R"
           href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.2.html"
         - text: "Hands-on Exercise 2.1: 1st Order Spatial Point Patterns Analysis Methods"
           href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.1.html"   
         - text: "Hands-on Exercise 2.2: 2nd Order Spatial Point Patterns Analysis Methods"
           href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.2.html"
         - text: "Hands-on Exercise 3: Network Constrained Spatial Point Patterns Analysis"
           href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3.html"    
         - text: "Hands-on Exercise 4: Spatial Weights and Applications"
           href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex4.html" 
         - text: "Hands-on Exercise 5.1: Global Measures of Spatial Autocorrelation"
           href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5.1.html" 
         - text: "Hands-on Exercise 5.2: Local Measures of Spatial Autocorrelation"
           href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5.2.html"   
         - text: "Hands-on Exercise 6: Geographical Segmentation with Spatially Constrained Clustering Techniques"
           href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex6.html"             
     - text: "In-class Exercise"
       menu: 
         - text: "In-class Exercise 1: Geospatial Data Science with R"
           href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"      
         - text: "In-class Exercise 2: Spatial Point Patterns Analysis: spatstat methods"
           href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"  
         - text: "In-class Exercise 3: Network Constrained Spatial Point Patterns Analysis"
           href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"  
         - text: "In-class Exercise 4: Geographically Weighted Summary Statistics - gwModel methods"
           href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"  
         - text: "In-class Exercise 5: Global and Local Measures of Spatial Autocorrelation: sfdep methods"
           href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html" 
     - text: "Take-Home Exercise"
       menu: 
         - text: "Take-Home Exercise 1"
           href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"  
         - text: "Take-Home Exercise 2"
           href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex02.html"  
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

